version: '3'

services:

  website:
    build: .
    ports:
      - "3001:3000"
    volumes:
      - ./src:/opt/reprosci
      - /mnt/reprosci:/mnt/reprosci
      - /mnt/reprosci_share:/mnt/reprosci_share
      - /data/reprosci:/data/reprosci
    env_file: .env.prod
    restart: always
    
  postgres:
    build:
        context: .
        dockerfile: Dockerfile.db
    env_file: .env.prod
    volumes:
      - /data/reprosci/postgres-data:/var/lib/postgresql/data
      - ./startdb:/docker-entrypoint-initdb.d
    restart: always