version: '3'

services:

  website:
    build: .
    ports:
      - "3001:3000"
    volumes:
      - /mnt/reprosci:/mnt/reprosci
    env_file: .env.prod
   
  postgres:
    build:
        context: .
        dockerfile: Dockerfile.db
    env_file: .env.prod
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./startdb:/docker-entrypoint-initdb.d