version: '3'

services:

  website:
    build: .
    ports:
      - "32756:3000"
    volumes:
      - ./src:/opt/reprosci
    env_file: .env.dev
   
  postgres:
    build:
        context: .
        dockerfile: Dockerfile.db
    env_file: .env.dev
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./startdb:/docker-entrypoint-initdb.d