development:
 data_dir:
  /mnt/reprosci/
 share_data_dir:
  /mnt/reprosci_share/
 data_server:
  ENV["DATA_URL"] 
 server_url:
  ENV["SERVER_URL"]

production:
 data_dir:
  /mnt/reprosci/
 share_data_dir:
  /mnt/reprosci_share/
 data_server:
  https://reprosci.epfl.ch/data/
#  ENV["DATA_URL"]
 server_url:
  https://reprosci.epfl.ch/
#  ENV["SERVER_URL"]